 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/technologies", type: :request do
  # Technology. As you add validations to Technology, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Technology.create! valid_attributes
      get technologies_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      technology = Technology.create! valid_attributes
      get technology_url(technology)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_technology_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      technology = Technology.create! valid_attributes
      get edit_technology_url(technology)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Technology" do
        expect {
          post technologies_url, params: { technology: valid_attributes }
        }.to change(Technology, :count).by(1)
      end

      it "redirects to the created technology" do
        post technologies_url, params: { technology: valid_attributes }
        expect(response).to redirect_to(technology_url(Technology.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Technology" do
        expect {
          post technologies_url, params: { technology: invalid_attributes }
        }.to change(Technology, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post technologies_url, params: { technology: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested technology" do
        technology = Technology.create! valid_attributes
        patch technology_url(technology), params: { technology: new_attributes }
        technology.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the technology" do
        technology = Technology.create! valid_attributes
        patch technology_url(technology), params: { technology: new_attributes }
        technology.reload
        expect(response).to redirect_to(technology_url(technology))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        technology = Technology.create! valid_attributes
        patch technology_url(technology), params: { technology: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested technology" do
      technology = Technology.create! valid_attributes
      expect {
        delete technology_url(technology)
      }.to change(Technology, :count).by(-1)
    end

    it "redirects to the technologies list" do
      technology = Technology.create! valid_attributes
      delete technology_url(technology)
      expect(response).to redirect_to(technologies_url)
    end
  end
end
